# Generated by Django 3.2.15 on 2026-05-22 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenplay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='剧本标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='剧本描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenplays', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '剧本',
                'verbose_name_plural': '剧本',
                'db_table': 'screenplays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenplayEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.IntegerField(verbose_name='分集序号')),
                ('episode_title', models.CharField(blank=True, default='', max_length=255, verbose_name='分集标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='原始文案内容')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='scripts.screenplay', verbose_name='所属剧本')),
            ],
            options={
                'verbose_name': '分集剧本',
                'verbose_name_plural': '分集剧本',
                'db_table': 'screenplay_episodes',
                'ordering': ['sort_order', 'episode_number'],
            },
        ),
        migrations.AddIndex(
            model_name='screenplayepisode',
            index=models.Index(fields=['screenplay', 'sort_order', 'episode_number'], name='episode_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='screenplayepisode',
            constraint=models.UniqueConstraint(fields=('screenplay', 'episode_number'), name='uniq_screenplay_episode_number'),
        ),
        migrations.AddIndex(
            model_name='screenplay',
            index=models.Index(fields=['user', '-created_at'], name='screenplays_user_created_idx'),
        ),
    ]
