version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: yunspire-backend
    env_file:
      - .env
    environment:
      - NO_PROXY=*.aliyuncs.com,localhost,127.0.0.1
    volumes:
      - ./output:/app/output
    ports:
      - "17177:17177"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: yunspire-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
