# Generated by Django 3.2.15 on 2026-03-19 05:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(blank=True, choices=[('static', '静态'), ('zoom_in', '推进'), ('zoom_out', '拉远'), ('pan_left', '左移'), ('pan_right', '右移'), ('tilt_up', '上摇'), ('tilt_down', '下摇'), ('dolly_in', '前推'), ('dolly_out', '后拉')], default='', max_length=50, verbose_name='运镜类型')),
                ('movement_params', models.JSONField(blank=True, default=dict, verbose_name='运镜参数')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '运镜',
                'verbose_name_plural': '运镜',
                'db_table': 'camera_movements',
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=1024, verbose_name='图片URL')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, verbose_name='缩略图URL')),
                ('generation_params', models.JSONField(default=dict, verbose_name='生成参数')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '生成图片',
                'verbose_name_plural': '生成图片',
                'db_table': 'generated_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiGridImageTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_image_url', models.URLField(max_length=1024, verbose_name='多宫格原图URL')),
                ('grid_rows', models.IntegerField(default=2, verbose_name='行数')),
                ('grid_cols', models.IntegerField(default=2, verbose_name='列数')),
                ('tile_gap', models.IntegerField(default=0, verbose_name='格子间距')),
                ('outer_padding', models.IntegerField(default=0, verbose_name='外边距')),
                ('split_config', models.JSONField(blank=True, default=dict, verbose_name='切图配置')),
                ('generation_params', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '多宫格图片任务',
                'verbose_name_plural': '多宫格图片任务',
                'db_table': 'multi_grid_image_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(verbose_name='序号')),
                ('scene_description', models.TextField(verbose_name='场景描述')),
                ('narration_text', models.TextField(verbose_name='旁白文案')),
                ('image_prompt', models.TextField(verbose_name='文生图提示词')),
                ('duration_seconds', models.FloatField(default=3.0, verbose_name='时长(秒)')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboards', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '分镜',
                'verbose_name_plural': '分镜',
                'db_table': 'storyboards',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='MultiGridTile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tile_index', models.IntegerField(verbose_name='切片序号')),
                ('row_index', models.IntegerField(verbose_name='行序号')),
                ('col_index', models.IntegerField(verbose_name='列序号')),
                ('crop_box', models.JSONField(blank=True, default=dict, verbose_name='裁切区域')),
                ('tile_image_url', models.URLField(max_length=1024, verbose_name='切片图片URL')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='content.multigridimagetask', verbose_name='多宫格任务')),
            ],
            options={
                'verbose_name': '多宫格切片',
                'verbose_name_plural': '多宫格切片',
                'db_table': 'multi_grid_tiles',
                'ordering': ['tile_index'],
            },
        ),
        migrations.AddField(
            model_name='multigridimagetask',
            name='storyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_grid_tasks', to='content.storyboard', verbose_name='分镜'),
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=1024, verbose_name='视频URL')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, verbose_name='缩略图URL')),
                ('duration', models.FloatField(default=0, verbose_name='时长(秒)')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('fps', models.IntegerField(default=24, verbose_name='帧率')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('generation_params', models.JSONField(default=dict, verbose_name='生成参数')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('camera_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.cameramovement', verbose_name='运镜')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.generatedimage', verbose_name='源图片')),
                ('model_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.storyboard', verbose_name='分镜')),
            ],
            options={
                'verbose_name': '生成视频',
                'verbose_name_plural': '生成视频',
                'db_table': 'generated_videos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='storyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.storyboard', verbose_name='分镜'),
        ),
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_stage_type', models.CharField(choices=[('image_generation', '文生图'), ('multi_grid_image', '多宫格图片')], default='multi_grid_image', max_length=20, verbose_name='来源阶段')),
                ('source_image_url', models.URLField(max_length=1024, verbose_name='源图片URL')),
                ('edited_image_url', models.URLField(max_length=1024, verbose_name='编辑后图片URL')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_params', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('width', models.IntegerField(default=0, verbose_name='宽度')),
                ('height', models.IntegerField(default=0, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
                ('multi_grid_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_images', to='content.multigridimagetask', verbose_name='来源多宫格任务')),
                ('multi_grid_tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_images', to='content.multigridtile', verbose_name='来源多宫格切片')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_images', to='content.storyboard', verbose_name='分镜')),
            ],
            options={
                'verbose_name': '图片编辑结果',
                'verbose_name_plural': '图片编辑结果',
                'db_table': 'edited_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRewrite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField(verbose_name='原始文本')),
                ('rewritten_text', models.TextField(blank=True, default='', verbose_name='改写后文本')),
                ('prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='生成元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelprovider', verbose_name='使用的模型')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_rewrite', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '文案改写',
                'verbose_name_plural': '文案改写',
                'db_table': 'content_rewrites',
            },
        ),
        migrations.AddField(
            model_name='cameramovement',
            name='storyboard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_movement', to='content.storyboard', verbose_name='分镜'),
        ),
        migrations.AddIndex(
            model_name='storyboard',
            index=models.Index(fields=['project', 'sequence_number'], name='storyboards_project_1829d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyboard',
            unique_together={('project', 'sequence_number')},
        ),
        migrations.AddIndex(
            model_name='multigridtile',
            index=models.Index(fields=['task', 'tile_index'], name='multi_grid__task_id_2ed938_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multigridtile',
            unique_together={('task', 'tile_index')},
        ),
        migrations.AddIndex(
            model_name='multigridimagetask',
            index=models.Index(fields=['storyboard', 'status'], name='multi_grid__storybo_ab6ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['storyboard', 'status'], name='generated_v_storybo_34a883_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['storyboard', 'status'], name='generated_i_storybo_5a3c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='editedimage',
            index=models.Index(fields=['storyboard', 'status'], name='edited_imag_storybo_8de7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='editedimage',
            index=models.Index(fields=['multi_grid_tile'], name='edited_imag_multi_g_016183_idx'),
        ),
    ]
