// Headless API surface for adapters and non-DOM orchestration.
//
// This barrel intentionally re-exports pure helpers, contracts, loading state,
// lifecycle operations, and renderer registry utilities without importing any
// framework wrapper. It is the safest entrypoint for React/Vue/Web packages.
export {
  DEFAULT_FILE_VIEWER_ARCHIVE_WORKER_PATH,
  DEFAULT_FILE_VIEWER_ARCHIVE_WASM_PATH,
  DEFAULT_FILE_VIEWER_CAD_DWF_WASM_PATH,
  DEFAULT_FILE_VIEWER_CAD_WASM_PATH,
  DEFAULT_FILE_VIEWER_CAD_WORKER_PATH,
  DEFAULT_FILE_VIEWER_DATA_SQL_WASM_URL,
  DEFAULT_FILE_VIEWER_DOCX_WORKER_JSZIP_PATH,
  DEFAULT_FILE_VIEWER_DOCX_WORKER_PATH,
  DEFAULT_FILE_VIEWER_RENDERER_ASSET_MANIFESTS,
  DEFAULT_FILE_VIEWER_SPREADSHEET_WORKER_PATH,
  DEFAULT_FILE_VIEWER_TYPST_COMPILER_WASM_URL,
  DEFAULT_FILE_VIEWER_TYPST_RENDERER_WASM_PACKAGE_PATH,
  DEFAULT_FILE_VIEWER_TYPST_RENDERER_WASM_URL,
  getFileViewerRendererAssetManifest,
  listFileViewerRendererAssetManifests,
  resolveFileViewerArchiveWasmUrl,
  resolveFileViewerArchiveWorkerUrl,
  resolveFileViewerAssetUrl,
  resolveFileViewerCadAssetUrls,
  resolveFileViewerDataSqlWasmUrl,
  resolveFileViewerDocxWorkerJsZipUrl,
  resolveFileViewerDocxWorkerUrl,
  resolveFileViewerDrawioViewerScriptUrl,
  resolveFileViewerRendererAssets,
  resolveFileViewerSpreadsheetWorkerUrl,
  resolveFileViewerTypstCompilerWasmUrl,
  resolveFileViewerTypstRendererWasmUrl,
} from './assets';
export type {
  FileViewerRendererAssetDefinition,
  FileViewerRendererAssetKind,
  FileViewerRendererAssetManifest,
  FileViewerRendererAssetOptionPath,
  FileViewerRendererAssetTarget,
  ResolveFileViewerAssetUrlOptions,
  ResolveFileViewerRendererAssetsOptions,
  ResolvedFileViewerCadAssetUrls,
  ResolvedFileViewerRendererAsset,
} from './assets';

export {
  ADAPTER_PRINT_REQUIRED_EXTENSIONS,
  createUnsupportedAvailability,
  DEFAULT_OPERATION_AVAILABILITY,
  DOM_PRINTABLE_EXTENSIONS,
  getRendererAvailability,
  isDomPrintableExtension,
  isKnownNonPrintableExtension,
  needsDedicatedPrintAdapter,
  NON_PRINTABLE_EXTENSIONS,
  resolvePrintAvailability,
} from './registry/capabilities';

export {
  DEFAULT_FILE_VIEWER_TEXT_CHUNK_OVERLAP,
  DEFAULT_FILE_VIEWER_TEXT_CHUNK_SIZE,
  DEFAULT_FILE_VIEWER_ZOOM_SCALE,
  buildFileViewerDocumentTextChunks,
  createEmptyFileViewerSearchState,
  createFileViewerZoomState,
  normalizeFileViewerAiOptions,
  normalizeFileViewerSearchOptions,
} from './features/document/model';

export {
  ARCHIVE_EXTENSIONS,
  DEFAULT_RENDERER_DEFINITIONS,
  DEFAULT_SUPPORTED_EXTENSIONS,
  IMAGE_EXTENSIONS,
  MODEL_EXTENSIONS,
  TEXT_EXTENSIONS,
} from './registry/formats';

export {
  FILE_VIEWER_BEFORE_OPERATION_ERROR_PREFIX,
  FILE_VIEWER_LIFECYCLE_HOOK_ERROR_MESSAGE_PREFIX,
  FILE_VIEWER_LIFECYCLE_HOOKS,
  FILE_VIEWER_OPERATION_LABELS,
  buildFileViewerLifecycleContext,
  buildFileViewerLifecycleContextFromNormalizedSource,
  buildFileViewerOperationContext,
  buildFileViewerOperationContextFromLifecycleState,
  cloneFileViewerOperationAvailability,
  createFileViewerLifecycleActions,
  createFileViewerLifecycleStateController,
  createFileViewerPublicApi,
  createFileViewerToolbarActions,
  createFileViewerToolbarControllerActionHandlers,
  createFileViewerToolbarZoomSyncSnapshot,
  DEFAULT_FILE_VIEWER_LIFECYCLE_HOOK_ERROR_LOGGER,
  DEFAULT_FILE_VIEWER_OPERATION_ERROR_LOGGER,
  dispatchFileViewerLifecycleEvent,
  dispatchFileViewerOperationAvailabilityChange,
  dispatchFileViewerOperationContextEvent,
  dispatchFileViewerZoomChange,
  emitFileViewerComponentLifecycleEvent,
  getFileViewerBeforeOperationHooks,
  getFileViewerLifecycleHookName,
  hasVisibleFileViewerToolbarActions,
  isFileViewerToolbarOperationPermitted,
  isFileViewerZoomButtonDisabled,
  normalizeFileViewerToolbar,
  reportFileViewerLifecycleHookError,
  reportFileViewerOperationError,
  resolveFileViewerBeforeOperationErrorMessage,
  resolveFileViewerLifecycleFallbackSource,
  resolveFileViewerLifecycleHookErrorMessage,
  resolveFileViewerOperationAvailability,
  resolveFileViewerToolbarPosition,
  resolveFileViewerToolbarState,
  resolveVisibleFileViewerToolbar,
  runFileViewerActiveUnloadComplete,
  runFileViewerActiveUnloadStart,
  runFileViewerBeforeOperation,
  runFileViewerLifecycleHook,
  runFileViewerToolbarAvailabilitySync,
  runFileViewerToolbarZoomSync,
  serializeFileViewerContext,
} from './lifecycle/operations';
export {
  FILE_VIEWER_BUILTIN_MESSAGES,
  FILE_VIEWER_DEFAULT_LOCALE,
  FILE_VIEWER_FALLBACK_LOCALE,
  createFileViewerTranslator,
  formatFileViewerMessage,
  normalizeFileViewerLocale,
  resolveFileViewerLocale,
  translateFileViewerMessage,
} from './i18n/messages';
export type {
  FileViewerI18nInput,
  FileViewerResolvedLocale,
  ResolveFileViewerI18nInput,
} from './i18n/messages';
export type {
  BuildFileViewerLifecycleContextFromNormalizedSourceInput,
  BuildFileViewerOperationContextFromLifecycleStateInput,
  BuildFileViewerLifecycleContextInput,
  BuiltFileViewerLifecycleContext,
  BuiltFileViewerOperationContext,
  CreateFileViewerLifecycleActionsInput,
  CreateFileViewerPublicApiInput,
  CreateFileViewerToolbarActionsInput,
  CreateFileViewerToolbarControllerActionHandlersInput,
  DispatchFileViewerLifecycleEventInput,
  DispatchFileViewerOperationAvailabilityChangeInput,
  DispatchFileViewerOperationContextEventInput,
  DispatchFileViewerZoomChangeInput,
  FileViewerActiveUnloadState,
  FileViewerLifecycleActions,
  FileViewerLifecycleComponentEmit,
  FileViewerLifecycleHookErrorLogger,
  FileViewerLifecycleStateController,
  FileViewerOperationErrorLogger,
  FileViewerToolbarActions,
  FileViewerToolbarControllerActionHandlers,
  FileViewerToolbarState,
  FileViewerToolbarZoomSyncSnapshot,
  FileViewerZoomButtonAction,
  ReportFileViewerLifecycleHookErrorInput,
  ReportFileViewerOperationErrorInput,
  ResolveFileViewerBeforeOperationErrorMessageInput,
  ResolveFileViewerLifecycleHookErrorMessageInput,
  ResolveFileViewerOperationAvailabilityInput,
  ResolveFileViewerToolbarStateInput,
  RunFileViewerActiveUnloadCompleteInput,
  RunFileViewerActiveUnloadStartInput,
  RunFileViewerBeforeOperationInput,
  RunFileViewerToolbarAvailabilitySyncInput,
  RunFileViewerToolbarZoomSyncInput,
  SerializedFileViewerContext,
} from './lifecycle/operations';

export {
  getFileViewerOptionsSearchParam,
  normalizeFileViewerTheme,
  parseFileViewerOptions,
  sanitizeFileViewerOptions,
  serializeFileViewerOptions,
  setFileViewerOptionsSearchParam,
} from './config/options';
export type {
  FileViewerSerializableCadOptions,
  FileViewerSerializableOptions,
  FileViewerSerializableToolbarOptions,
} from './config/options';

export {
  resolveFileViewerPresentationState,
} from './presentation/state';
export type {
  FileViewerPresentationState,
  ResolveFileViewerPresentationStateInput,
} from './presentation/state';

export {
  createRendererRegistry,
} from './registry/registry';

export {
  createFileViewerRendererDispatcher,
} from './rendering/dispatcher';
export type {
  CreateFileViewerRendererDispatcherOptions,
  FileViewerRendererDispatcher,
  FileViewerRendererHandlerEntry,
} from './rendering/dispatcher';

export {
  buildFileRenderContextFromLoadContext,
  createFileRenderHandlerRegistry,
  createFileRenderHandlerLoader,
} from './rendering/handler';
export type {
  CreateFileRenderHandlerLoaderOptions,
  CreateFileRenderHandlerRegistryOptions,
  FileRenderHandlerRegistryResult,
} from './rendering/handler';

export {
  DEFAULT_FILE_VIEWER_SOURCE_FILENAME,
  decodeFilename,
  getExtension,
  normalizeFileExtension,
  normalizeFilename,
  normalizeSource,
  readFileViewerBuffer,
  readFileViewerDataUrl,
  readFileViewerText,
  resolveFileViewerSourceFilename,
  wrapFileViewerFileRef,
} from './source';
export type {
  FileViewerReadResult,
} from './source';

export {
  cancelFileViewerPreviewRequest,
  DEFAULT_FILE_VIEWER_PREVIEW_LOAD_ERROR_LOGGER,
  DEFAULT_FILE_VIEWER_STREAMING_PDF_FILENAME,
  DEFAULT_PDF_RANGE_CHUNK_SIZE,
  FILE_VIEWER_PREVIEW_LOAD_ERROR_PREFIXES,
  FILE_VIEWER_REMOTE_MISSING_DATA_ERROR_MESSAGE,
  applyFileViewerEmptyPreviewState,
  applyFileViewerPreviewFilenameState,
  applyFileViewerPreviewRequestResetState,
  applyFileViewerPreviewSourceUrlState,
  applyFileViewerReadPreviewState,
  applyFileViewerRenderReadinessState,
  commitFileViewerEmptyPreviewResetState,
  commitFileViewerLoadStartState,
  commitFileViewerPreviewRequestStartState,
  commitFileViewerRemoteDownloadState,
  createFileViewerEmptyPreviewState,
  createFileViewerLoadStartState,
  createFileViewerPreviewRequestResetState,
  createFileViewerPreviewStateTarget,
  createFileViewerReadPreviewState,
  createFileViewerRenderCompleteState,
  createFileViewerRequestController,
  createFileViewerRequestScope,
  createFileViewerSourceLoadingActionHandlers,
  createFileViewerStreamingPdfPlaceholderFile,
  finalizeFileViewerPreviewLoadState,
  hasFileViewerPreviewSource,
  isFileViewerAbortError,
  isSameOriginUrl,
  normalizeFileViewerSourceUrl,
  normalizePdfStreamingMode,
  reportFileViewerMissingRemoteData,
  reportFileViewerPreviewLoadError,
  resolveFileViewerFileRefSourcePlan,
  resolveFileViewerLoadStartMessage,
  resolveFileViewerMissingRemoteDataErrorMessage,
  resolveFileViewerPageHref,
  resolveFileViewerPreviewLoadErrorMessage,
  resolveFileViewerPreviewRequestReason,
  resolveFileViewerRemoteSourcePlan,
  runFileViewerLocalFilePreview,
  runFileViewerPreviewComponentUnmount,
  runFileViewerPreviewRequest,
  runFileViewerPreviewSourceChange,
  runFileViewerRemoteFilePreview,
  runFileViewerReadAndRenderFile,
  runFileViewerStreamingPdfPreview,
  shouldStreamPdfUrl,
} from './source/loading';
export type {
  CancelFileViewerPreviewRequestInput,
  CommitFileViewerEmptyPreviewResetStateInput,
  CommitFileViewerLoadStartStateInput,
  CommitFileViewerPreviewRequestStartStateInput,
  CommitFileViewerRenderCompleteStateInput,
  CommitFileViewerRemoteDownloadStateInput,
  CreateFileViewerLoadStartStateInput,
  CreateFileViewerPreviewStateTargetInput,
  CreateFileViewerReadPreviewStateInput,
  CreateFileViewerRenderCompleteStateInput,
  CreateFileViewerSourceLoadingActionHandlersInput,
  FileViewerEmptyPreviewState,
  FileViewerFileRefSourcePlan,
  FileViewerLocalFilePreviewState,
  FileViewerLoadStartState,
  FileViewerLocationLike,
  FileViewerMutableAccessor,
  FileViewerPreviewComponentUnmountState,
  FileViewerPreviewLoadErrorKind,
  FileViewerPreviewLoadErrorLogger,
  FileViewerPreviewLoadErrorPrefixes,
  FileViewerPreviewRequestResetState,
  FileViewerPreviewRequestRunState,
  FileViewerReadAndRenderFileState,
  FileViewerReadPreviewState,
  FileViewerRemoteDownloadState,
  FileViewerRemoteFileDownloadInput,
  FileViewerRemoteFilePreviewErrorKind,
  FileViewerRemoteFilePreviewState,
  FileViewerRemoteSourcePlan,
  FileViewerRenderCompleteState,
  FileViewerRenderReadinessState,
  FileViewerRequestController,
  FileViewerRequestScope,
  FileViewerSourceLoadingActionHandlers,
  FileViewerStreamingPdfPreviewState,
  FinalizeFileViewerPreviewLoadStateInput,
  MutableFileViewerPreviewFilenameState,
  MutableFileViewerPreviewRequestState,
  MutableFileViewerPreviewSourceUrlState,
  MutableFileViewerPreviewState,
  MutableFileViewerReadPreviewState,
  MutableFileViewerRenderReadinessState,
  ReportFileViewerMissingRemoteDataInput,
  ReportFileViewerPreviewLoadErrorInput,
  ResolveFileViewerFileRefSourcePlanInput,
  ResolveFileViewerMissingRemoteDataErrorMessageInput,
  ResolveFileViewerPreviewLoadErrorMessageInput,
  ResolveFileViewerPreviewRequestReasonInput,
  RunFileViewerLocalFilePreviewInput,
  RunFileViewerPreviewComponentUnmountInput,
  RunFileViewerPreviewRequestInput,
  RunFileViewerPreviewSourceChangeInput,
  RunFileViewerReadAndRenderFileInput,
  RunFileViewerRemoteFilePreviewInput,
  RunFileViewerStreamingPdfPreviewInput,
} from './source/loading';

export {
  DEFAULT_FILE_VIEWER_STATE_THEME,
  DEFAULT_FILE_VIEWER_UNSUPPORTED_DESCRIPTION,
  FILE_VIEWER_PREVIEW_MESSAGES,
  createFileViewerEmptyState,
  createFileViewerErrorState,
  createFileViewerPreviewLoadingState,
  createFileViewerReadyState,
  createFileViewerUnsupportedState,
  formatFileViewerErrorMessage,
  normalizeFileViewerErrorMessage,
} from './viewer/state';
export type {
  FileViewerErrorMessageFormatter,
} from './viewer/state';

export {
  buildFileViewerWatermarkBackgroundImage,
  buildFileViewerWatermarkInlineStyle,
  buildFileViewerWatermarkStyle,
  buildFileViewerWatermarkSvg,
  normalizeFileViewerWatermark,
  resolveFileViewerWatermarkPresentationState,
} from './features/watermark';
export type {
  FileViewerWatermarkPresentationState,
  FileViewerWatermarkStyle,
} from './features/watermark';

export type {
  FileRenderContext,
  FileRenderExportAdapter,
  FileRenderExportMode,
  FileRenderExportOptions,
  FileRenderHandler,
  FileRenderHandlerComposite,
  FileViewerBuiltinRendererPreset,
  FileViewerAiOptions,
  FileViewerArchiveOptions,
  FileViewerBeforeOperation,
  FileViewerCadDwfLineWeightMode,
  FileViewerCadOptions,
  FileViewerCadRenderer,
  FileViewerComponentEmits,
  FileViewerComponentEventMap,
  FileViewerComponentProps,
  FileViewerDocumentAnchor,
  FileViewerDocumentChunk,
  FileViewerDocxOptions,
  FileViewerDrawingOptions,
  FileViewerDownloadOptions,
  FileViewerEvent,
  FileViewerEventHandler,
  FileViewerEventType,
  FileViewerExportHtmlOptions,
  FileViewerFileRef,
  FileViewerGeoOptions,
  FileViewerInstance,
  FileViewerLifecycleContext,
  FileViewerLifecycleHooks,
  FileViewerLifecyclePhase,
  FileViewerI18nOptions,
  FileViewerLocale,
  FileViewerMessageKey,
  FileViewerMessageParams,
  FileViewerMessageResolver,
  FileViewerMessages,
  FileViewerOperationAvailability,
  FileViewerOperationContext,
  FileViewerOperationType,
  FileViewerOptions,
  FileViewerPdfOptions,
  FileViewerPrintOptions,
  FileViewerPublicApi,
  FileViewerRenderStateKind,
  FileViewerRenderedInstance,
  FileViewerRendererCategory,
  FileViewerSearchMatch,
  FileViewerSearchOptions,
  FileViewerSearchProvider,
  FileViewerSearchState,
  FileViewerSource,
  FileViewerSourceKind,
  FileViewerSpreadsheetOptions,
  FileViewerStateDescriptor,
  FileViewerStateTheme,
  FileViewerThemeMode,
  FileViewerToolbarActionMap,
  FileViewerToolbarOptions,
  FileViewerToolbarPosition,
  FileViewerTypstOptions,
  FileViewerWatermarkOptions,
  FileViewerZoomProvider,
  FileViewerZoomState,
  NormalizedFileViewerSource,
  RenderSurface,
  RendererCapability,
  RendererDefinition,
  RendererLoadContext,
  RendererLoader,
  RendererPlugin,
  RendererRegistry,
  RendererSession,
  ViewerCapabilityState,
  ViewerLifecycleContext,
  ViewerOperationContext,
} from './contracts/types';
