"""提示词模板可配置的 Client 参数定义。"""

from copy import deepcopy


PARAM_TYPE_LABELS = {
    'string': '字符串',
    'integer': '整数',
    'number': '数字',
    'boolean': '布尔值',
    'json': 'JSON 对象',
}


STAGE_CLIENT_PARAM_SPECS = {
    'rewrite': [
        {
            'key': 'max_tokens',
            'label': '最大 Token',
            'type': 'integer',
            'default': 4096,
            'min': 1,
            'max': 65536,
            'description': '控制单次输出长度上限。',
        },
        {
            'key': 'temperature',
            'label': '温度',
            'type': 'number',
            'default': 0.7,
            'min': 0,
            'max': 2,
            'step': 0.1,
            'description': '控制改写的发散程度。',
        },
        {
            'key': 'top_p',
            'label': 'Top P',
            'type': 'number',
            'default': 1,
            'min': 0,
            'max': 1,
            'step': 0.05,
            'description': '控制采样概率范围。',
        },
    ],
    'asset_extraction': [
        {
            'key': 'max_tokens',
            'label': '最大 Token',
            'type': 'integer',
            'default': 4096,
            'min': 1,
            'max': 65536,
            'description': '控制抽取结果长度上限。',
        },
        {
            'key': 'temperature',
            'label': '温度',
            'type': 'number',
            'default': 0.3,
            'min': 0,
            'max': 2,
            'step': 0.1,
            'description': '建议保持较低温度，减少结构抖动。',
        },
        {
            'key': 'top_p',
            'label': 'Top P',
            'type': 'number',
            'default': 1,
            'min': 0,
            'max': 1,
            'step': 0.05,
            'description': '控制采样概率范围。',
        },
    ],
    'storyboard': [
        {
            'key': 'max_tokens',
            'label': '最大 Token',
            'type': 'integer',
            'default': 40960,
            'min': 1,
            'max': 131072,
            'description': '分镜生成通常需要更高输出上限。',
        },
        {
            'key': 'temperature',
            'label': '温度',
            'type': 'number',
            'default': 0.8,
            'min': 0,
            'max': 2,
            'step': 0.1,
            'description': '适度提高温度有助于分镜创意。',
        },
        {
            'key': 'top_p',
            'label': 'Top P',
            'type': 'number',
            'default': 1,
            'min': 0,
            'max': 1,
            'step': 0.05,
            'description': '控制采样概率范围。',
        },
    ],
    'camera_movement': [
        {
            'key': 'max_tokens',
            'label': '最大 Token',
            'type': 'integer',
            'default': 4096,
            'min': 1,
            'max': 65536,
            'description': '控制运镜描述输出长度。',
        },
        {
            'key': 'temperature',
            'label': '温度',
            'type': 'number',
            'default': 0.6,
            'min': 0,
            'max': 2,
            'step': 0.1,
            'description': '控制运镜方案的发散程度。',
        },
        {
            'key': 'top_p',
            'label': 'Top P',
            'type': 'number',
            'default': 1,
            'min': 0,
            'max': 1,
            'step': 0.05,
            'description': '控制采样概率范围。',
        },
    ],
    'image_generation': [
        {
            'key': 'negative_prompt',
            'label': '负向提示词',
            'type': 'string',
            'default': '',
            'description': '用于抑制不希望出现的元素。',
        },
        {
            'key': 'ratio',
            'label': '画面比例',
            'type': 'string',
            'default': '1:1',
            'description': '传给文生图 Client 的比例参数。',
        },
        {
            'key': 'resolution',
            'label': '分辨率档位',
            'type': 'string',
            'default': '2k',
            'description': '如 2k、4k，具体取值由模型决定。',
        },
        {
            'key': 'width',
            'label': '宽度',
            'type': 'integer',
            'default': 1024,
            'min': 64,
            'max': 4096,
            'description': '输出图片宽度。',
        },
        {
            'key': 'height',
            'label': '高度',
            'type': 'integer',
            'default': 1024,
            'min': 64,
            'max': 4096,
            'description': '输出图片高度。',
        },
        {
            'key': 'steps',
            'label': '采样步数',
            'type': 'integer',
            'default': 20,
            'min': 1,
            'max': 200,
            'description': '控制生成迭代步数。',
        },
        {
            'key': 'sample_count',
            'label': '生成数量',
            'type': 'integer',
            'default': 1,
            'min': 1,
            'max': 8,
            'description': '单次请求返回的图片数量。',
        },
    ],
    'multi_grid_image': [
        {
            'key': 'negative_prompt',
            'label': '负向提示词',
            'type': 'string',
            'default': '',
            'description': '用于抑制不希望出现的元素。',
        },
        {
            'key': 'ratio',
            'label': '画面比例',
            'type': 'string',
            'default': '1:1',
            'description': '传给多宫格文生图 Client 的比例参数。',
        },
        {
            'key': 'resolution',
            'label': '分辨率档位',
            'type': 'string',
            'default': '2k',
            'description': '如 2k、4k，具体取值由模型决定。',
        },
        {
            'key': 'width',
            'label': '宽度',
            'type': 'integer',
            'default': 1024,
            'min': 64,
            'max': 4096,
            'description': '输出原图宽度。',
        },
        {
            'key': 'height',
            'label': '高度',
            'type': 'integer',
            'default': 1024,
            'min': 64,
            'max': 4096,
            'description': '输出原图高度。',
        },
        {
            'key': 'steps',
            'label': '采样步数',
            'type': 'integer',
            'default': 20,
            'min': 1,
            'max': 200,
            'description': '控制生成迭代步数。',
        },
        {
            'key': 'sample_count',
            'label': '生成数量',
            'type': 'integer',
            'default': 1,
            'min': 1,
            'max': 8,
            'description': '单次请求返回的图片数量。',
        },
    ],
    'image_edit': [
        {
            'key': 'mask_url',
            'label': '蒙版地址',
            'type': 'string',
            'default': '',
            'description': '可选的编辑蒙版 URL。',
        },
        {
            'key': 'strength',
            'label': '重绘强度',
            'type': 'number',
            'default': 0.35,
            'min': 0,
            'max': 1,
            'step': 0.05,
            'description': '控制编辑对原图的保留程度。',
        },
        {
            'key': 'width',
            'label': '宽度',
            'type': 'integer',
            'default': 1024,
            'min': 64,
            'max': 4096,
            'description': '输出图片宽度。',
        },
        {
            'key': 'height',
            'label': '高度',
            'type': 'integer',
            'default': 1024,
            'min': 64,
            'max': 4096,
            'description': '输出图片高度。',
        },
        {
            'key': 'negative_prompt',
            'label': '负向提示词',
            'type': 'string',
            'default': '',
            'description': '用于抑制不希望出现的元素。',
        },
    ],
    'video_generation': [
        {
            'key': 'duration',
            'label': '视频时长',
            'type': 'integer',
            'default': 5,
            'min': 1,
            'max': 60,
            'description': '单位秒。',
        },
        {
            'key': 'fps',
            'label': '帧率',
            'type': 'integer',
            'default': 24,
            'min': 1,
            'max': 120,
            'description': '仅在执行器支持时生效。',
        },
        {
            'key': 'aspect_ratio',
            'label': '画面比例',
            'type': 'string',
            'default': '16:9',
            'description': '传给图生视频 Client 的比例参数。',
        },
        {
            'key': 'resolution',
            'label': '分辨率档位',
            'type': 'string',
            'default': '',
            'description': '如 720p、1080p，具体取值由模型决定。',
        },
        {
            'key': 'negative_prompt',
            'label': '负向提示词',
            'type': 'string',
            'default': '',
            'description': '用于抑制不希望出现的元素。',
        },
        {
            'key': 'poll_interval',
            'label': '轮询间隔',
            'type': 'integer',
            'default': 5,
            'min': 1,
            'max': 120,
            'description': '异步任务状态查询间隔，单位秒。',
        },
        {
            'key': 'max_wait_time',
            'label': '最长等待时间',
            'type': 'integer',
            'default': 600,
            'min': 1,
            'max': 7200,
            'description': '异步任务最长等待时间，单位秒。',
        },
    ],
}


def get_stage_client_param_specs(stage_type: str):
    """获取某个阶段的参数 schema。"""
    specs = STAGE_CLIENT_PARAM_SPECS.get(stage_type, [])
    return deepcopy(specs)


def get_stage_client_param_spec_map(stage_type: str):
    """按 key 返回某个阶段的参数 schema。"""
    return {item['key']: item for item in get_stage_client_param_specs(stage_type)}

