# Generated by Django 3.2.15 on 2026-03-19 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptDebugArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('text', '文本'), ('storyboard_bundle', '分镜集合'), ('storyboard_item', '分镜条目'), ('image', '图片'), ('video', '视频')], max_length=30, verbose_name='资产类型')),
                ('stage_type', models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('sequence_number', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='资产内容')),
                ('preview_text', models.TextField(blank=True, default='', verbose_name='预览文本')),
                ('preview_image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='预览图片')),
                ('preview_video_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='预览视频')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否固定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_debug_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '提示词调试资产',
                'verbose_name_plural': '提示词调试资产',
                'db_table': 'prompt_debug_artifacts',
                'ordering': ['stage_type', 'sequence_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplateSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_sets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '提示词集',
                'verbose_name_plural': '提示词集',
                'db_table': 'prompt_template_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型')),
                ('template_content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='变量定义')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, help_text='该提示词模板默认使用的AI模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to='models.modelprovider', verbose_name='模型提供商')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='prompts.prompttemplateset', verbose_name='提示词集')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'db_table': 'prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='PromptDebugSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='会话名称')),
                ('stage_type', models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型')),
                ('draft_template_content', models.TextField(blank=True, default='', verbose_name='草稿模板内容')),
                ('draft_variables', models.JSONField(blank=True, default=dict, verbose_name='草稿变量定义')),
                ('latest_variable_values', models.JSONField(blank=True, default=dict, verbose_name='最近变量值')),
                ('latest_input_payload', models.JSONField(blank=True, default=dict, verbose_name='最近输入载荷')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近运行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_debug_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('latest_source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_sessions', to='prompts.promptdebugartifact', verbose_name='最近引用资产')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_debug_sessions', to='models.modelprovider', verbose_name='调试模型')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_sessions', to='prompts.prompttemplate', verbose_name='提示词模板')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_sessions', to='prompts.prompttemplateset', verbose_name='提示词集')),
            ],
            options={
                'verbose_name': '提示词调试会话',
                'verbose_name_plural': '提示词调试会话',
                'db_table': 'prompt_debug_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptDebugRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('template_snapshot', models.TextField(blank=True, default='', verbose_name='模板快照')),
                ('variable_values', models.JSONField(blank=True, default=dict, verbose_name='变量值')),
                ('input_payload', models.JSONField(blank=True, default=dict, verbose_name='输入载荷')),
                ('resolved_variables', models.JSONField(blank=True, default=dict, verbose_name='解析后变量')),
                ('rendered_prompt', models.TextField(blank=True, default='', verbose_name='渲染后提示词')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='原始响应')),
                ('parsed_output', models.JSONField(blank=True, default=dict, verbose_name='解析后输出')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='延迟(毫秒)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_debug_runs', to='models.modelprovider', verbose_name='使用模型')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='prompts.promptdebugsession', verbose_name='调试会话')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_runs', to='prompts.promptdebugartifact', verbose_name='来源资产')),
            ],
            options={
                'verbose_name': '提示词调试运行',
                'verbose_name_plural': '提示词调试运行',
                'db_table': 'prompt_debug_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promptdebugartifact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='prompts.promptdebugrun', verbose_name='调试运行'),
        ),
        migrations.AddField(
            model_name='promptdebugartifact',
            name='source_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='prompts.promptdebugartifact', verbose_name='来源资产'),
        ),
        migrations.CreateModel(
            name='GlobalVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='变量键')),
                ('value', models.TextField(blank=True, default='', verbose_name='变量值')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='assets/images/%Y/%m/', verbose_name='图片文件')),
                ('variable_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON对象'), ('image', '图片')], default='string', max_length=20, verbose_name='变量类型')),
                ('scope', models.CharField(choices=[('system', '系统级'), ('user', '用户级')], default='user', max_length=20, verbose_name='作用域')),
                ('group', models.CharField(blank=True, default='', max_length=100, verbose_name='分组')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_variables', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '全局变量',
                'verbose_name_plural': '全局变量',
                'db_table': 'global_variables',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='prompttemplateset',
            index=models.Index(fields=['is_active', 'is_default'], name='prompt_temp_is_acti_d5ab82_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['template_set', 'stage_type', 'is_active'], name='prompt_temp_templat_a85d4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('template_set', 'stage_type'), name='uniq_active_template_per_stage'),
        ),
        migrations.AddIndex(
            model_name='promptdebugsession',
            index=models.Index(fields=['created_by', 'stage_type'], name='prompt_debu_created_c2b948_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugsession',
            index=models.Index(fields=['prompt_template', '-updated_at'], name='prompt_debu_prompt__04ef1f_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugrun',
            index=models.Index(fields=['session', '-created_at'], name='prompt_debu_session_16e4df_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugrun',
            index=models.Index(fields=['stage_type', 'status'], name='prompt_debu_stage_t_127360_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['created_by', 'artifact_type'], name='prompt_debu_created_d6ec04_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['stage_type', 'artifact_type'], name='prompt_debu_stage_t_0930da_idx'),
        ),
        migrations.AddIndex(
            model_name='promptdebugartifact',
            index=models.Index(fields=['run', 'sequence_number'], name='prompt_debu_run_id_0f2ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['scope', 'is_active'], name='global_vari_scope_c0f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['created_by', 'is_active'], name='global_vari_created_b0dddf_idx'),
        ),
        migrations.AddIndex(
            model_name='globalvariable',
            index=models.Index(fields=['group', 'is_active'], name='global_vari_group_16ddb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalvariable',
            unique_together={('key', 'created_by', 'scope')},
        ),
    ]
