# Generated by Django 3.2.15 on 2026-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptdebugartifact',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('image_edit', '图片编辑'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AlterField(
            model_name='promptdebugrun',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('image_edit', '图片编辑'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AlterField(
            model_name='promptdebugsession',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('image_edit', '图片编辑'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='stage_type',
            field=models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('image_edit', '图片编辑'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型'),
        ),
    ]
