# Generated by Django 3.2.15 on 2026-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_auto_20260319_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptdebugsession',
            name='draft_client_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='草稿执行参数'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='client_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行参数'),
        ),
    ]
