# Generated by Django 3.2.15 on 2026-03-19 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('episode_number', models.IntegerField(blank=True, null=True, verbose_name='分集序号')),
                ('episode_title', models.CharField(blank=True, default='', max_length=255, verbose_name='分集标题')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('original_topic', models.TextField(verbose_name='原始主题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('queued', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('paused', '已暂停')], default='draft', max_length=20, verbose_name='状态')),
                ('jianying_draft_path', models.CharField(blank=True, default='', max_length=500, verbose_name='剪映草稿路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('prompt_template_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='prompts.prompttemplateset', verbose_name='提示词集')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='作品名称')),
                ('description', models.TextField(blank=True, verbose_name='作品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'db_table': 'series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('rewrite', '剧本精修'), ('asset_extraction', '资产抽取'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('multi_grid_image', '多宫格图片'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频'), ('image_edit', '图片编辑')], max_length=20, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目阶段',
                'verbose_name_plural': '项目阶段',
                'db_table': 'project_stages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('load_balance_strategy', models.CharField(choices=[('round_robin', '轮询'), ('random', '随机'), ('weighted', '权重随机'), ('least_loaded', '最少负载')], default='weighted', max_length=20, verbose_name='负载均衡策略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('camera_providers', models.ManyToManyField(blank=True, related_name='camera_configs', to='models.ModelProvider', verbose_name='运镜生成模型')),
                ('image_providers', models.ManyToManyField(blank=True, related_name='image_configs', to='models.ModelProvider', verbose_name='文生图模型')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_config', to='projects.project', verbose_name='项目')),
                ('rewrite_providers', models.ManyToManyField(blank=True, related_name='rewrite_configs', to='models.ModelProvider', verbose_name='文案改写模型')),
                ('storyboard_providers', models.ManyToManyField(blank=True, related_name='storyboard_configs', to='models.ModelProvider', verbose_name='分镜生成模型')),
                ('video_providers', models.ManyToManyField(blank=True, related_name='video_configs', to='models.ModelProvider', verbose_name='图生视频模型')),
            ],
            options={
                'verbose_name': '项目模型配置',
                'verbose_name_plural': '项目模型配置',
                'db_table': 'project_model_configs',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssetBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bindings', to='prompts.globalvariable', verbose_name='资产')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_bindings', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目资产绑定',
                'verbose_name_plural': '项目资产绑定',
                'db_table': 'project_asset_bindings',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='projects.series', verbose_name='所属作品'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='EpisodeTaskQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('pipeline', '完整流程'), ('stage', '单阶段')], default='pipeline', max_length=20, verbose_name='任务类型')),
                ('stage_name', models.CharField(blank=True, default='', max_length=32, verbose_name='阶段名称')),
                ('status', models.CharField(choices=[('waiting', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='waiting', max_length=20, verbose_name='队列状态')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='任务参数')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_task_queues', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tasks', to='projects.project', verbose_name='分集项目')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_tasks', to='projects.series', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': '分集任务队列',
                'verbose_name_plural': '分集任务队列',
                'db_table': 'episode_task_queue',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['user', '-created_at'], name='series_user_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('project', 'stage_type')},
        ),
        migrations.AddIndex(
            model_name='projectassetbinding',
            index=models.Index(fields=['project', 'created_at'], name='proj_asset_proj_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectassetbinding',
            unique_together={('project', 'asset')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status', '-created_at'], name='projects_user_id_5d20b1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['series', 'sort_order', 'episode_number'], name='projects_series_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('episode_number__isnull', False), ('series__isnull', False)), fields=('series', 'episode_number'), name='uniq_series_episode_number'),
        ),
        migrations.AddIndex(
            model_name='episodetaskqueue',
            index=models.Index(fields=['series', 'status', 'created_at'], name='episode_tas_series__18f8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='episodetaskqueue',
            index=models.Index(fields=['project', 'status', 'created_at'], name='episode_tas_project_7152ad_idx'),
        ),
        migrations.AddIndex(
            model_name='episodetaskqueue',
            index=models.Index(fields=['celery_task_id'], name='episode_tas_celery__c73a3a_idx'),
        ),
    ]
